import type { ClientRecord, CriminalCaseRecord } from "../../types";

export const mockClients: ClientRecord[] = [
  {
    client_id: "CL-2026-001",
    client: {
      client_id: "CL-2026-001",
      name: "Maria Santos",
      age: 34,
      sex: "Female",
      civil_status: "Married",
      religion: "Catholic",
      educational_attainment: "College Graduate",
      citizenship: "Filipino",
      language_dialect: "Tagalog",
    },
    client_details: {
      address: "Davao City",
      contact_no: "09171234567",
      email: "maria.santos@example.com",
      individual_monthly_income: "18000",
      spouse: "Jose Santos",
      address_of_spouse: "Davao City",
      contact_no_of_spouse: "09179876543",
      representative_name: "Jose Santos",
      representative_age: 36,
      representative_sex: "Male",
      representative_civil_status: "Married",
      representative_address: "Davao City",
      representative_contact_no: "09179876543",
      representative_relationship: "Spouse",
      representative_email: "jose.santos@example.com",
      detained: false,
      detained_since: "",
      place_of_detention: "",
    },
    client_classification: {
      flag_senior: false,
      flag_cicl: false,
      flag_female: true,
      flag_urban: true,
      flag_rural: false,
      flag_drugs: false,
      flag_foreign_national: false,
      flag_vawc_victim: false,
      flag_refugee_evacuee: false,
      flag_law_enforcer: false,
      flag_tenant_agrarian: false,
      flag_ofw_land_based: false,
      flag_ofw_sea_based: false,
      flag_arrested_terrorism: false,
      flag_indigenous_people: false,
      flag_pwd: false,
      flag_former_rebel_fve: false,
      flag_torture_victim: false,
      flag_trafficking_victim: false,
      flag_voluntary_rehab_petitioner: false,
      classification_notes: "Walk-in applicant; eligible under income screening.",
    },
  },
  {
    client_id: "CL-2026-002",
    client: {
      client_id: "CL-2026-002",
      name: "Ramon Dela Cruz",
      age: 42,
      sex: "Male",
      civil_status: "Single",
      religion: "Christian",
      educational_attainment: "High School",
      citizenship: "Filipino",
      language_dialect: "Cebuano",
    },
    client_details: {
      address: "Panabo City",
      contact_no: "09182345678",
      email: "",
      individual_monthly_income: "12000",
      spouse: "",
      address_of_spouse: "",
      contact_no_of_spouse: "",
      representative_name: "Ana Dela Cruz",
      representative_age: 39,
      representative_sex: "Female",
      representative_civil_status: "Single",
      representative_address: "Panabo City",
      representative_contact_no: "09183456789",
      representative_relationship: "Sibling",
      representative_email: "",
      detained: true,
      detained_since: "2026-03-11",
      place_of_detention: "Davao City Jail",
    },
    client_classification: {
      flag_senior: false,
      flag_cicl: false,
      flag_female: false,
      flag_urban: false,
      flag_rural: true,
      flag_drugs: true,
      flag_foreign_national: false,
      flag_vawc_victim: false,
      flag_refugee_evacuee: false,
      flag_law_enforcer: false,
      flag_tenant_agrarian: false,
      flag_ofw_land_based: false,
      flag_ofw_sea_based: false,
      flag_arrested_terrorism: false,
      flag_indigenous_people: false,
      flag_pwd: false,
      flag_former_rebel_fve: false,
      flag_torture_victim: false,
      flag_trafficking_victim: false,
      flag_voluntary_rehab_petitioner: false,
      classification_notes: "Detained client referred for custodial assistance.",
    },
  },
];

export const mockCases: CriminalCaseRecord[] = [
  {
    case_id: "CASE-2026-001",
    client_id: "CL-2026-001",
    intake_record: {
      control_no: "CR-2026-0001",
      form_date: "2026-05-01",
      region: "XI",
      district_office: "Davao City District Office",
      party_represented: "Accused",
      applicant_role: "Accused",
      applicant_role_other: "",
      nature_of_request: "Legal representation",
      nature_of_case: "Criminal",
    },
    representative: {
      rep_name: "Jose Santos",
      rep_age: 36,
      rep_sex: "Male",
      civil_status: "Married",
      rep_address: "Davao City",
      rep_contact_no: "09179876543",
      relationship_to_applicant: "Spouse",
    },
    adverse_party: {
      role: "Complainant",
      name: "People of the Philippines",
      address: "Davao City Prosecutor's Office",
    },
    cases: {
      title_of_case: "People v. Santos",
      case_no: "RTC-25-1938",
      court_body: "Regional Trial Court Branch 17",
      status_of_case: "Ongoing",
      last_action_taken: "Arraignment completed; pre-trial scheduled.",
      date_of_confinement: "",
      place_of_detention: "",
      location_type: "Urban",
      cause_of_action: "Alleged theft",
      facts_of_case: "Client is accused in a theft complaint and seeks representation for court proceedings.",
      pending_in_court: true,
      cause_of_termination: "",
      date_of_termination: "",
    },
    last_updated: "2026-05-05",
  },
  {
    case_id: "CASE-2026-002",
    client_id: "CL-2026-002",
    intake_record: {
      control_no: "CR-2026-0002",
      form_date: "2026-04-24",
      region: "XI",
      district_office: "Davao del Norte District Office",
      party_represented: "Accused",
      applicant_role: "Accused",
      applicant_role_other: "",
      nature_of_request: "Custodial assistance",
      nature_of_case: "Criminal",
    },
    representative: {
      rep_name: "Ana Dela Cruz",
      rep_age: 39,
      rep_sex: "Female",
      civil_status: "Single",
      rep_address: "Panabo City",
      rep_contact_no: "09183456789",
      relationship_to_applicant: "Sibling",
    },
    adverse_party: {
      role: "Complainant",
      name: "People of the Philippines",
      address: "Davao del Norte Prosecutor's Office",
    },
    cases: {
      title_of_case: "People v. Dela Cruz",
      case_no: "MTC-26-0914",
      court_body: "Municipal Trial Court Panabo",
      status_of_case: "Pending",
      last_action_taken: "Awaiting preliminary conference.",
      date_of_confinement: "2026-03-11",
      place_of_detention: "Davao City Jail",
      location_type: "Rural",
      cause_of_action: "Drug-related offense",
      facts_of_case: "Client was detained in relation to a drug-related offense and requires custodial assistance.",
      pending_in_court: true,
      cause_of_termination: "",
      date_of_termination: "",
    },
    last_updated: "2026-05-03",
  },
  {
    case_id: "CASE-2026-003",
    client_id: "CL-2026-002",
    intake_record: {
      control_no: "CR-2026-0003",
      form_date: "2026-04-30",
      region: "XI",
      district_office: "Davao del Norte District Office",
      party_represented: "Accused",
      applicant_role: "Accused",
      applicant_role_other: "",
      nature_of_request: "Representation",
      nature_of_case: "Criminal",
    },
    representative: {
      rep_name: "Ana Dela Cruz",
      rep_age: 39,
      rep_sex: "Female",
      civil_status: "Single",
      rep_address: "Panabo City",
      rep_contact_no: "09183456789",
      relationship_to_applicant: "Sibling",
    },
    adverse_party: {
      role: "Complainant",
      name: "People of the Philippines",
      address: "Davao del Norte Prosecutor's Office",
    },
    cases: {
      title_of_case: "People v. Dela Cruz",
      case_no: "MTC-26-0822",
      court_body: "Municipal Trial Court Panabo",
      status_of_case: "Terminated",
      last_action_taken: "Case dismissed after compliance review.",
      date_of_confinement: "2026-02-20",
      place_of_detention: "Davao City Jail",
      location_type: "Rural",
      cause_of_action: "Public disturbance",
      facts_of_case: "Client was charged after a public disturbance report and the case was later dismissed.",
      pending_in_court: true,
      cause_of_termination: "Dismissed",
      date_of_termination: "2026-05-02",
    },
    last_updated: "2026-05-02",
  },
];
